web/router.ex
defmodule Ioquiz.Router do
  use Ioquiz.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Ioquiz.Auth, repo: Ioquiz.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Ioquiz do
    pipe_through :browser # Use the default browser stack

    get  "/", PageController, :index

    get  "/students/:username", StudentController, :show
    get  "/students/:username/history", StudentController, :history
    get  "/students/:username/lesson/:lesson_id/review", StudentController, :review
    get  "/students/:username/lesson/:lesson_id/quiz", StudentController, :quiz
    post  "/students/:username/lesson/:lesson_id/quiz", StudentController, :submit_quiz
    post  "/students", StudentController, :assign_lesson
    delete  "/students/:student_id/lesson/:lesson_id", StudentController, :unassign_lesson

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", Ioquiz do
    pipe_through [:browser, :authenticate_user, :check_role_level] # Use the default browser stack

    resources "/users", UserController
    resources "/subjects", SubjectController, except: [:show] do
      resources "/lessons", LessonController, except: [:show] do
        resources "/questions", QuestionController, except: [:show] do
          resources "/items", ItemController, except: [:show]
        end
        resources "/terms", TermController, except: [:show]
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Ioquiz do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Ioquiz.LayoutView do
  use Ioquiz.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ioQuiz</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

    <div class="ui menu" style="margin-bottom:4rem;">
      <div class="brand header item">
        ioQuiz
      </div>

      <%= if @current_user.role_level < 3 do %>
        <a class="item">Dashboard</a>
      <% end %>

      <%= if @current_user.role_level == 1 do %>
        <%= link "Users", to: user_path(@conn, :index), class: "item" %>
      <% end %>
      <%= if @current_user.role_level == 2 do %>
        <%= link "Students", to: user_path(@conn, :index), class: "item" %>
      <% end %>

      <%= if @current_user.role_level == 3 do %>
        <%= link raw("<i class=\"large home icon\"></i>"), to: student_path(@conn, :show, @current_user.username), class: "item" %>
        <%= link "History", to: student_path(@conn, :history, @current_user.username), class: "item" %>
      <% end %>

      <%= if @current_user.role_level < 3 do %>
        <%= link "Subjects", to: subject_path(@conn, :index), class: "item" %>
      <% end %>

      <div class="right menu">
        <div class="logged-in-name header item">
          <%= @current_user.name %>
        </div>

        <%= link "Log Out", to: session_path(@conn, :delete, @current_user), method: "delete", form: [class: "item"], class: "ui button" %>
      </div>
    </div>

    <div class="ui text container">
      <%= if get_flash(@conn, :info) do %>
        <div class="ui success message">
          <p><%= get_flash(@conn, :info) %></p>
        </div>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <div class="ui error message">
          <p><%= get_flash(@conn, :error) %></p>
        </div>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <div class="footer" style="padding:2rem 0;"></div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/public.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ioQuiz - A more effective learning strategy.</title>

    <link href="https://fonts.googleapis.com/css?family=Bitter|Lora|Source+Sans+Pro:400.400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

    <!-- Top Menu -->
    <div class="ui secondary menu" style="margin-bottom:3rem;">
      <div class="brand header item" style="font-size:1.4em;">
        ioQuiz
      </div>
      <div class="right menu">
        <%= if @current_user do %>
          <%= link "Log Out", to: session_path(@conn, :delete, @current_user), method: "delete", form: [class: "item"], class: "ui green button" %>
        <% else %>
          <%= link "Log in", to: session_path(@conn, :new), style: "padding: 1em 2em 0 0;" %></a>
        <% end %>
      </div>
    </div>

    <!-- Masthead -->
    <div class="ui vertical masthead center aligned segment" style="border-bottom: none;">
      <div class="ui text container">
        <h1 class="ui header">You study hard but you still get poor results. Why?</h1>
        <h2 class="ui header">Because you're doing it wrong.</h2>
        <p><img src="<%= static_path(@conn, "/images/study-hard.jpg") %>"></p>
      </div>
    </div>

    <!-- Main -->
    <%= render @view_module, @view_template, assigns %>

    <!-- Footer -->
    <div class="ui vertical center aligned footer segment">
      <div class="ui text container">
        <p>Copyright &copy; 2016 ioQuiz — All Rights Reserved</p>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ioQuiz</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <style>
    .sessions > .container,
    #login-form {
      height: 100%;
    }
    #login-form .column {
      max-width: 450px;
    }
    #login-form .header {
      margin-top: -240px;
    }
    </style>
  </head>

  <body class="sessions">

    <div class="ui text container">
      <div style="min-height:70px;margin-top:40px;">
        <%= if get_flash(@conn, :info) do %>
          <div class="ui success message">
            <p><%= get_flash(@conn, :info) %></p>
          </div>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <div class="ui error message">
            <p><%= get_flash(@conn, :error) %></p>
          </div>
        <% end %>
      </div>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>