web/router.ex
defmodule Ioquiz.Router do
  use Ioquiz.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Ioquiz.Auth, repo: Ioquiz.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Ioquiz do
    pipe_through :browser # Use the default browser stack

    get  "/", PageController, :index

    get  "/students/:username", StudentController, :show
    get  "/students/:username/history", StudentController, :history
    get  "/students/:username/lesson/:lesson_id/review", StudentController, :review
    get  "/students/:username/lesson/:lesson_id/quiz", StudentController, :quiz
    post  "/students/:username/lesson/:lesson_id/quiz", StudentController, :submit_quiz
    post  "/students", StudentController, :assign_lesson
    delete  "/students/:student_id/lesson/:lesson_id", StudentController, :unassign_lesson

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", Ioquiz do
    pipe_through [:browser, :authenticate_user, :check_role_level] # Use the default browser stack

    resources "/users", UserController
    resources "/subjects", SubjectController, except: [:show] do
      resources "/lessons", LessonController, except: [:show] do
        resources "/questions", QuestionController, except: [:show] do
          resources "/items", ItemController, except: [:show]
        end
        resources "/terms", TermController, except: [:show]
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Ioquiz do
  #   pipe_through :api
  # end
end

web/models/lesson.ex
defmodule Ioquiz.Lesson do
  use Ioquiz.Web, :model

  schema "lessons" do
    field :title, :string
    belongs_to :subject, Ioquiz.Subject
    has_many :questions, Ioquiz.Question
    has_many :terms, Ioquiz.Term
    many_to_many :users, Ioquiz.User, join_through: "student_lessons"

    timestamps()
  end
  
  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title])
    |> validate_required([:title])
    |> assoc_constraint(:subject)
  end
end

web/controllers/lesson_controller.ex
defmodule Ioquiz.LessonController do
  use Ioquiz.Web, :controller

  alias Ioquiz.Subject
  alias Ioquiz.Lesson

  def index(conn, %{"subject_id" => subject_id}) do
    subject = Repo.get!(Subject, subject_id)
    lessons = Repo.all(subject_lessons(subject))

    render(conn, "index.html", subject: subject, lessons: lessons)
  end

  def new(conn, %{"subject_id" => subject_id}) do
    subject = Repo.get!(Subject, subject_id)
    changeset = Lesson.changeset(%Lesson{})

    render(conn, "new.html", subject: subject, changeset: changeset)
  end

  def create(conn, %{"subject_id" => subject_id, "lesson" => lesson_params}) do
    subject = Repo.get!(Subject, subject_id)

    changeset = 
      subject
      |> build_assoc(:lessons)
      |> Lesson.changeset(lesson_params)

    case Repo.insert(changeset) do
      {:ok, _lesson} ->
        conn
        |> put_flash(:info, "Lesson created successfully.")
        |> redirect(to: subject_lesson_path(conn, :index, subject))
      {:error, changeset} ->
        render(conn, "new.html", subject: subject, changeset: changeset)
    end
  end

  def edit(conn, %{"subject_id" => subject_id, "id" => id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(subject_lessons(subject), id)

    changeset = Lesson.changeset(lesson)

    render(conn, "edit.html", subject: subject, lesson: lesson, changeset: changeset)
  end

  def update(conn, %{"subject_id" => subject_id, "id" => id, "lesson" => lesson_params}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(subject_lessons(subject), id)

    changeset = Lesson.changeset(lesson, lesson_params)

    case Repo.update(changeset) do
      {:ok, _lesson} ->
        conn
        |> put_flash(:info, "Lesson updated successfully.")
        |> redirect(to: subject_lesson_path(conn, :index, subject))
      {:error, changeset} ->
        render(conn, "edit.html", subject: subject, lesson: lesson, changeset: changeset)
    end
  end

  def delete(conn, %{"subject_id" => subject_id, "id" => id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(subject_lessons(subject), id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(lesson)

    conn
    |> put_flash(:info, "Lesson deleted successfully.")
    |> redirect(to: subject_lesson_path(conn, :index, subject))
  end

  defp subject_lessons(subject) do
    assoc(subject, :lessons)
  end
end

web/views/lesson_view.ex
defmodule Ioquiz.LessonView do
  use Ioquiz.Web, :view
end

web/templates/lesson/edit.html.eex
<h2 class="ui header">Edit Lesson</h2>

<%= render "form.html", changeset: @changeset,
                        action: subject_lesson_path(@conn, :update, @subject, @lesson) %>

<p><%= link "Back", to: subject_lesson_path(@conn, :index, @subject) %></p>

web/templates/lesson/form.html.eex
<%= form_for @changeset, @action, [class: "ui large form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="ui negative message">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :title %>
    <%= text_input f, :title %>
    <%= error_tag f, :title %>
  </div>

  <div class="field">
    <%= submit "Submit", class: "ui primary button" %>
  </div>
<% end %>

web/templates/lesson/index.html.eex
<div class="ui breadcrumb">
  <%= link "Subjects", to: subject_path(@conn, :index), class: "section" %>
  <div class="divider"> / </div>
  <div class="active section">Lessons</div>
</div>

<h2 class="ui header"><%= @subject.title %></h2>

<p><%= link "New lesson", to: subject_lesson_path(@conn, :new, @subject), class: "mini ui primary basic button" %></p>

<table class="ui basic table">
  <tbody>
<%= for lesson <- @lessons do %>
    <tr>
      <td> <%= link lesson.title, to: subject_lesson_term_path(@conn, :index, @subject, lesson) %></td>

      <td class="right aligned">
        <%= link "Edit", to: subject_lesson_path(@conn, :edit, @subject, lesson), class: "mini ui primary basic button" %>
        <%= link "Delete", to: subject_lesson_path(@conn, :delete, @subject, lesson), method: :delete, form: [style: "display:inline-block"], data: [confirm: "Are you sure?"], class: "mini negative ui basic button" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/lesson/new.html.eex
<h2 class="ui header">New lesson</h2>

<%= render "form.html", changeset: @changeset,
                        action: subject_lesson_path(@conn, :create, @subject) %>

<p><%= link "Back", to: subject_lesson_path(@conn, :index, @subject) %></p>