web/router.ex
defmodule Ioquiz.Router do
  use Ioquiz.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Ioquiz.Auth, repo: Ioquiz.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Ioquiz do
    pipe_through :browser # Use the default browser stack

    get  "/", PageController, :index

    get  "/students/:username", StudentController, :show
    get  "/students/:username/history", StudentController, :history
    get  "/students/:username/lesson/:lesson_id/review", StudentController, :review
    get  "/students/:username/lesson/:lesson_id/quiz", StudentController, :quiz
    post  "/students/:username/lesson/:lesson_id/quiz", StudentController, :submit_quiz
    post  "/students", StudentController, :assign_lesson
    delete  "/students/:student_id/lesson/:lesson_id", StudentController, :unassign_lesson

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", Ioquiz do
    pipe_through [:browser, :authenticate_user, :check_role_level] # Use the default browser stack

    resources "/users", UserController
    resources "/subjects", SubjectController, except: [:show] do
      resources "/lessons", LessonController, except: [:show] do
        resources "/questions", QuestionController, except: [:show] do
          resources "/items", ItemController, except: [:show]
        end
        resources "/terms", TermController, except: [:show]
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Ioquiz do
  #   pipe_through :api
  # end
end

web/models/item.ex
defmodule Ioquiz.Item do
  use Ioquiz.Web, :model

  schema "items" do
    field :content, :string
    field :type, :integer, default: 1
    field :status, :integer, default: 1
    belongs_to :question, Ioquiz.Question

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content, :type, :status])
    |> validate_required([:content])
  end
end

web/controllers/item_controller.ex
defmodule Ioquiz.ItemController do
  use Ioquiz.Web, :controller

  alias Ioquiz.Subject
  alias Ioquiz.Lesson
  alias Ioquiz.Question
  alias Ioquiz.Item

  def index(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "question_id" => question_id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    question = Repo.get!(Question, question_id)
    items = Repo.all(question_items(question))

    render(conn, "index.html", subject: subject, lesson: lesson, question: question, items: items)
  end

  def new(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "question_id" => question_id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    question = Repo.get!(Question, question_id)

    changeset = 
      question
      |> build_assoc(:items)
      |> Item.changeset()

    render(conn, "new.html", subject: subject, lesson: lesson, question: question, changeset: changeset)
  end

  def create(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "question_id" => question_id, "item" => item_params}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    question = Repo.get!(Question, question_id)

    changeset = 
      question
      |> build_assoc(:items)
      |> Item.changeset(item_params)

    case Repo.insert(changeset) do
      {:ok, _item} ->
        conn
        |> put_flash(:info, "Item created successfully.")
        |> redirect(to: subject_lesson_question_item_path(conn, :index, subject, lesson, question))
      {:error, changeset} ->
        render(conn, "new.html", subject: subject, lesson: lesson, question: question, changeset: changeset)
    end
  end

  def edit(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "question_id" => question_id, "id" => id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    question = Repo.get!(Question, question_id)
    item = Repo.get!(question_items(question), id)

    changeset = Item.changeset(item)

    render(conn, "edit.html", subject: subject, lesson: lesson, question: question, item: item, changeset: changeset)
  end

  def update(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "question_id" => question_id, "id" => id, "item" => item_params}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    question = Repo.get!(Question, question_id)
    item = Repo.get!(question_items(question), id)

    changeset = Item.changeset(item, item_params)

    case Repo.update(changeset) do
      {:ok, _item} ->
        conn
        |> put_flash(:info, "Item updated successfully.")
        |> redirect(to: subject_lesson_question_item_path(conn, :index, subject, lesson, question))
      {:error, changeset} ->
        render(conn, "edit.html", subject: subject, lesson: lesson, question: question, item: item, changeset: changeset)
    end
  end

  def delete(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "question_id" => question_id, "id" => id}) do
    item = Repo.get!(Item, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(item)

    conn
    |> put_flash(:info, "Item deleted successfully.")
    |> redirect(to: subject_lesson_question_item_path(conn, :index, subject_id, lesson_id, question_id))
  end

  defp question_items(question) do
    assoc(question, :items)
  end
end

web/views/item_view.ex
defmodule Ioquiz.ItemView do
  use Ioquiz.Web, :view
end

web/templates/item/edit.html.eex
<h2 class="ui header">Edit Item</h2>
<h2>No Header Class</h2>

<%= render "form.html", changeset: @changeset,
                        action: subject_lesson_question_item_path(@conn, :update, @subject, @lesson, @question, @item) %>

<p><%= link "Back", to: subject_lesson_question_item_path(@conn, :index, @subject, @lesson, @question) %></p>

web/templates/item/form.html.eex
<%= form_for @changeset, @action, [class: "ui large form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="ui negative message">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :content %>
    <%= textarea f, :content %>
    <%= error_tag f, :content %>
  </div>

  <div class="field">
    <%= label f, :type %>
    <%= number_input f, :type %>
    <%= error_tag f, :type %>
  </div>

  <div class="field">
    <%= label f, :status %>
    <%= number_input f, :status %>
    <%= error_tag f, :status %>
  </div>

  <div class="field">
    <%= submit "Submit", class: "ui primary button" %>
  </div>
<% end %>

web/templates/item/index.html.eex
<div class="ui breadcrumb">
  <%= link "Subjects", to: subject_path(@conn, :index), class: "section" %>
  <i class="right chevron icon divider"></i>
  <%= link "Lessons", to: subject_lesson_path(@conn, :index, @subject), class: "section" %>
  <i class="right chevron icon divider"></i>
  <%= link "Questions", to: subject_lesson_question_path(@conn, :index, @subject, @lesson), class: "section" %>
  <i class="right chevron icon divider"></i>
  <div class="active section">Items</div>
</div>

<h2 class="ui header"><%= @subject.title %></h2>
<h3 class="ui header"><%= @lesson.title %></h3>

<div><%= raw @question.question %></div>

<p><%= link "Add Item", to: subject_lesson_question_item_path(@conn, :new, @subject, @lesson, @question), class: "mini ui primary basic button" %></p>

<table class="ui basic table">
  <thead>
    <tr>
      <th>Content</th>
      <th>Type</th>
      <th>Status</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for item <- @items do %>
    <tr>
      <td><%= raw item.content %></td>
      <td><%= item.type %></td>
      <td><%= item.status %></td>

      <td class="text-right">
        <%= link "Edit", to: subject_lesson_question_item_path(@conn, :edit, @subject, @lesson, @question, item), class: "mini ui primary basic button" %>
        <%= link "Delete", to: subject_lesson_question_item_path(@conn, :delete, @subject, @lesson, @question, item), method: :delete, data: [confirm: "Are you sure?"], class: "mini negative ui basic button" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "Add Item", to: subject_lesson_question_item_path(@conn, :new, @subject, @lesson, @question), class: "mini ui primary basic button" %>

web/templates/item/new.html.eex
<h2 class="ui header">New Item</h2>

<%= render "form.html", changeset: @changeset,
                        action: subject_lesson_question_item_path(@conn, :create, @subject, @lesson, @question) %>

<p><%= link "Back", to: subject_lesson_question_item_path(@conn, :index, @subject, @lesson, @question) %></p>