web/router.ex
defmodule Ioquiz.Router do
  use Ioquiz.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Ioquiz.Auth, repo: Ioquiz.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Ioquiz do
    pipe_through :browser # Use the default browser stack

    get  "/", PageController, :index

    get  "/students/:username", StudentController, :show
    get  "/students/:username/history", StudentController, :history
    get  "/students/:username/lesson/:lesson_id/review", StudentController, :review
    get  "/students/:username/lesson/:lesson_id/quiz", StudentController, :quiz
    post  "/students/:username/lesson/:lesson_id/quiz", StudentController, :submit_quiz
    post  "/students", StudentController, :assign_lesson
    delete  "/students/:student_id/lesson/:lesson_id", StudentController, :unassign_lesson

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", Ioquiz do
    pipe_through [:browser, :authenticate_user, :check_role_level] # Use the default browser stack

    resources "/users", UserController
    resources "/subjects", SubjectController, except: [:show] do
      resources "/lessons", LessonController, except: [:show] do
        resources "/questions", QuestionController, except: [:show] do
          resources "/items", ItemController, except: [:show]
        end
        resources "/terms", TermController, except: [:show]
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Ioquiz do
  #   pipe_through :api
  # end
end

web/models/question.ex
defmodule Ioquiz.Question do
  use Ioquiz.Web, :model

  schema "questions" do
    field :question, :string
    field :type, :integer, default: 1 # 1 = identification, 2 = multiple choice, etc..
    field :status, :integer, default: 1 # 1 = active, 2 = inactive, 3 = draft
    belongs_to :lesson, Ioquiz.Lesson
    has_many :items, Ioquiz.Item

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:question, :type, :status])
    |> validate_required([:question])
  end
end

web/controllers/question_controller.ex
defmodule Ioquiz.QuestionController do
  use Ioquiz.Web, :controller

  alias Ioquiz.Subject
  alias Ioquiz.Lesson
  alias Ioquiz.Question

  def index(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    questions = Repo.all(lesson_questions(lesson))

    render(conn, "index.html", subject: subject, lesson: lesson, questions: questions, question_count: Enum.count(questions))
  end

  def new(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)

    changeset = 
      lesson
      |> build_assoc(:questions)
      |> Question.changeset()

    render(conn, "new.html", subject: subject, lesson: lesson, changeset: changeset)
  end

  def create(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "question" => question_params}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)

    changeset = 
      lesson
      |> build_assoc(:questions)
      |> Question.changeset(question_params)

    case Repo.insert(changeset) do
      {:ok, _question} ->
        conn
        |> put_flash(:info, "Question created successfully.")
        |> redirect(to: subject_lesson_question_path(conn, :index, subject, lesson))
      {:error, changeset} ->
        render(conn, "new.html", subject: subject, lesson: lesson, changeset: changeset)
    end
  end

  def edit(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "id" => id}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    question = Repo.get!(lesson_questions(lesson), id)

    changeset = Question.changeset(question)

    render(conn, "edit.html", subject: subject, lesson: lesson, question: question, changeset: changeset)
  end

  def update(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "id" => id, "question" => question_params}) do
    subject = Repo.get!(Subject, subject_id)
    lesson = Repo.get!(Lesson, lesson_id)
    question = Repo.get!(lesson_questions(lesson), id)

    changeset = Question.changeset(question, question_params)

    case Repo.update(changeset) do
      {:ok, _question} ->
        conn
        |> put_flash(:info, "Question updated successfully.")
        |> redirect(to: subject_lesson_question_path(conn, :index, subject, lesson))
      {:error, changeset} ->
        render(conn, "edit.html", subject: subject, lesson: lesson, question: question, changeset: changeset)
    end
  end

  def delete(conn, %{"subject_id" => subject_id, "lesson_id" => lesson_id, "id" => id}) do
    question = Repo.get!(Question, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(question)

    conn
    |> put_flash(:info, "Question deleted successfully.")
    |> redirect(to: subject_lesson_question_path(conn, :index, subject_id, lesson_id))
  end

  defp lesson_questions(lesson) do
    assoc(lesson, :questions)
  end
end

web/views/question_view.ex
defmodule Ioquiz.QuestionView do
  use Ioquiz.Web, :view
end

web/templates/question/edit.html.eex
<h2 class="ui header">Edit Question</h2>

<%= render "form.html", changeset: @changeset,
                        action: subject_lesson_question_path(@conn, :update, @subject, @lesson, @question) %>

<p><%= link "Back", to: subject_lesson_question_path(@conn, :index, @subject, @lesson) %></p>

web/templates/question/form.html.eex
<%= form_for @changeset, @action, [class: "ui large form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="ui negative message">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :question %>
    <%= textarea f, :question %>
    <%= error_tag f, :question %>
  </div>

  <div class="field">
    <%= label f, :type %>
    <%= number_input f, :type %>
    <%= error_tag f, :type %>
  </div>

  <div class="field">
    <%= label f, :status %>
    <%= number_input f, :status %>
    <%= error_tag f, :status %>
  </div>

  <div class="field">
    <%= submit "Submit", class: "ui primary button" %>
  </div>
<% end %>

web/templates/question/index.html.eex
<div class="ui breadcrumb">
  <%= link "Subjects", to: subject_path(@conn, :index), class: "section" %>
  <i class="right chevron icon divider"></i>
  <%= link "Lessons", to: subject_lesson_path(@conn, :index, @subject), class: "section" %>
  <i class="right chevron icon divider"></i>
  <div class="active section">Questions</div>
</div>

<h2 class="ui header"><%= @subject.title %></h2>
<h3 class="ui header"><%= @lesson.title %></h3>

<p><b><%= @question_count %> Questions</b> | <%= link "Add Question", to: subject_lesson_question_path(@conn, :new, @subject, @lesson), class: "mini ui primary basic button" %></p>

<table id="terms-table" class="ui basic table">
  <thead>
    <tr>
      <th>Question</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for question <- @questions do %>
    <tr>
      <td class="definition"><%= raw question.question %></td>

      <td class="top aligned right aligned">
        <%= link "View", to: subject_lesson_question_item_path(@conn, :index, @subject, @lesson, question), class: "mini ui primary basic button" %>
        <%= link "Edit", to: subject_lesson_question_path(@conn, :edit, @subject, @lesson, question), class: "mini ui primary basic button" %>
        <%= link "Delete", to: subject_lesson_question_path(@conn, :delete, @subject, @lesson, question), method: :delete, form: [style: "display:inline-block"], data: [confirm: "Are you sure?"], class: "mini negative ui basic button" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "Add Question", to: subject_lesson_question_path(@conn, :new, @subject, @lesson), class: "mini ui primary basic button" %>

web/templates/question/new.html.eex
<h2 class="ui header">New Question</h2>

<%= render "form.html", changeset: @changeset,
                        action: subject_lesson_question_path(@conn, :create, @subject, @lesson) %>

<p><%= link "Back", to: subject_lesson_question_path(@conn, :index, @subject, @lesson) %></p>